Fix Zero Price Market Order
sei-protocol/sei-chain pull request #764
Opened 2023-05-08 16:27 UTC by Kbhat1

## Describe your changes and provide context
- Updates `IsDecimalMultipleOf` to return true for zero (which is multiple)
- Fixes issue with Market Orders where zero price (which is allowed) was giving error because it previously wasn't a multiple of tick size
- Adds extra error to when user specifies zero quantity

## Testing performed to validate your change
- Tested e2e local placing orders
- Updated unit test

2023-05-08 23:41 UTC, LCyson requested changes
can we remove the libnitro_replayer and add unit tests

2023-05-09 01:30 UTC, Kbhat1 commented
> can we remove the libnitro_replayer and add unit tests

Updated

2023-05-09 01:35 UTC, codchen approved these changes

2023-05-09 04:57 UTC, LCyson approved these changes

2023-05-09 13:34 UTC, merged