feat: crypto.com provider
sei-protocol/sei-chain pull request #948
Opened 2023-06-30 17:47 UTC by alexanderbez

## Describe your changes and provide context

## Testing performed to validate your change

2023-07-07 13:25 UTC, yzang2019 reviewed
Can you modify config.example.toml to add crypto as well?

2023-07-07 14:20 UTC, philipsu522 approved these changes

2023-07-07 14:20 UTC, philipsu522 commented on oracle/price-feeder/oracle/provider/crypto.go
> +	if endpoint.Name != config.ProviderCrypto {
shoudl we error here? what is the reasoning behind setting it to crypto.com if it was misconfigured?

2023-07-07 15:04 UTC, alexanderbez commented on oracle/price-feeder/oracle/provider/crypto.go
> +	if endpoint.Name != config.ProviderCrypto {
So this is how all the other providers are implemented, along with the crypto.com one ported from umee. Although, I do agree it should error instead.

If we do that, we should do it for all providers and create an issue for it :)

2023-07-07 15:05 UTC, alexanderbez commented
Updated @yzang2019 :)

2023-07-21 15:35 UTC, udpatil requested changes

2023-07-21 15:35 UTC, udpatil commented on oracle/price-feeder/config.example.toml
> +chain_denom = "usol"
This is usei intentionally to have some moving price feed available on Atlantic 2 for usei

2023-07-21 15:36 UTC, udpatil commented on oracle/price-feeder/config.example.toml
> +chain_denom = "usol"
sorry @alexanderbez forgot to update this comment, can we make this change before merging?

2023-07-21 20:11 UTC, udpatil approved these changes

2023-07-23 20:24 UTC, merged